# Generated by Django 5.2.1 on 2025-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title_en',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_name_en',
            field=models.CharField(max_length=139, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_name_ru',
            field=models.CharField(max_length=139, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='networks',
            name='network_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='networks',
            name='network_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option_name_en',
            field=models.CharField(max_length=145, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option_name_ru',
            field=models.CharField(max_length=145, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_teach_en',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_teach_ru',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
